spring.application.name=notification-service
server.port=8081

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group-v2
spring.kafka.consumer.auto-offset-reset=latest

# Use STRING Serializer & Deserializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379

# Kafka Listener Settings
spring.kafka.listener.ack-mode=record
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.consumer.max-poll-records=1
spring.kafka.consumer.properties.max.poll.interval.ms=300000


# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohitpachar0108@gmail.com
spring.mail.password=cali tknw tcze izix
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Actuator — expose all endpoints
management.endpoints.web.exposure.include=health,info,metrics,kafka
management.endpoint.health.show-details=always
management.info.env.enabled=true

# App info shown at /actuator/info
info.app.name=Notification Service
info.app.version=1.0.0
info.app.port=8081
info.app.description=Kafka-Based Real-Time Notification Service
info.app.kafka.topic=ecommerce-events
info.app.kafka.group=notification-group-v2
info.app.university=Central University of Rajasthan
info.app.student=Mohit (2022BTCSE020)